version: '3.9'

services:
  lookup-app:
    environment:
      - REDIS_HOST=lookup-redis
      - REDIS_PORT=6379
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: lookup-app
    ports:
      - "8080:8080"
    networks:
      - lookup-network

  lookup-redis:
    container_name: lookup-redis
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - lookup-network

networks:
  lookup-network: